Add kafka backoff timeout in ms
aiven/aiven-kafka-connect-http pull request #22
Opened 2021-04-12 09:39 UTC by willyborankin

2021-04-12 10:23 UTC, tvainika commented on src/main/java/io/aiven/kafka/connect/http/config/HttpSinkConfig.java
> +                "The retry backoff notify Kafka connect to retry delivering a message batch "
Should it say that the unit is milliseconds here?

2021-04-12 13:05 UTC, ivanyu commented on src/main/java/io/aiven/kafka/connect/http/config/HttpSinkConfig.java
> +                        }
Why can't it be less than the default? E.g. 3 seconds, 100 ms?

Also, there's `ConfigDef.Range` class for checking ranges :)

2021-04-12 14:16 UTC, ivanyu commented
Also please mind the backward compatibility. In the current implementation, new option with the default kind of breaks it. I'm not saying we can't do this, but this should be though out and explicitly stated somewhere in the commit/PR description.

2021-04-13 15:05 UTC, willyborankin commented
@ivanyu fixed comment and PR message

2021-04-14 08:27 UTC, ivanyu requested changes
Please update the docs https://github.com/aiven/aiven-kafka-connect-http/blob/master/docs/sink-connector-config-options.rst

2021-04-14 11:25 UTC, willyborankin commented
@ivanyu Will prepare separate PR, there are some issue which need to be fixed in docs

2021-04-14 12:48 UTC, ivanyu approved these changes

2021-04-14 12:48 UTC, merged